"""change data a little2

Revision ID: 4ebdeaea1653
Revises: 321ccc7c4834
Create Date: 2025-02-17 18:51:10.411367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebdeaea1653'
down_revision = '321ccc7c4834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=16), nullable=True))
        batch_op.alter_column('reservation_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('confirm', 'none', 'cancel', name='modified_type_enum'),
               nullable=True)
        batch_op.drop_column('modified_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_type', sa.VARCHAR(length=7), nullable=True))
        batch_op.alter_column('reservation_status',
               existing_type=sa.Enum('confirm', 'none', 'cancel', name='modified_type_enum'),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
